# This is a basic workflow to help you get started with Actions

name: CI

on: [push, pull_request]

jobs:
  lint:
    runs-on: ubuntu-latest
    env:
      PYTHON: 3.9
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python ${{ env.PYTHON }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ env.PYTHON }}
    - name: Python info
      run: |
        which python
        python --version
    - name: Install Tox
      run: |
        python -m pip install --upgrade pip
        python -m pip install tox
    - name: Check format
      run: tox -e format
    - name: Run linters
      continue-on-error: true
      run: tox -e lint
